spring:
  application:
    name: JWT-SECURITY-SERVICE
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898
  
  
  
#Provides eureka location(optional)
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Generating instance ID(optional)
#eureka.instance.instance-id=${spring.application.name}:${random.value}

#REGISTER WITH EUREKA AS CLIENT(bydefault also true,if u not mention as true then also ok)
#eureka.client.register-with-eureka=true
#ENABLE FETCH OTHER MicroService DATA
#eureka.client.fetch-registry=true

#THIS APPLICATION LINK WITH CONFIG SERVER APPLICATION(CLIENT LINK WITH SERVER)
#spring.config.import=optional:configserver:http://localhost:8888